packages: []

allowBuilds:
  '@homebridge/node-pty-prebuilt-multiarch': true
  '@parcel/watcher': true
  electron: true
  electron-winstaller: true
  esbuild: true
onlyBuiltDependencies:
  - "@homebridge/node-pty-prebuilt-multiarch"
  - "electron"
